name: "Hello Actions"
description: "sample blah blah blah"
author: "sowmya.v@zemosolabs.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"